"""Generate `sample_qa.md` from a real run (Phase 7 task 5).

Every answer in that file is produced by calling the actual pipeline, then
written out verbatim. Nothing is hand-written, so the document cannot drift
from what the app really says - which is the point of the task.

    python tests/gen_sample_qa.py

Rewrites `sample_qa.md` in place. Safe to re-run after any change to the guard
copy, the thresholds or the LLM provider.
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

if hasattr(sys.stdout, "reconfigure"):  # Windows cp1252 console chokes on the en dash
    sys.stdout.reconfigure(encoding="utf-8")

from src.query import config
from src.query.answer import answer_question
from src.query.llm import get_llm

# Chosen to cover every behaviour the PRD names: a factual answer per
# attribute family, the procedural path, and each kind of refusal.
QUESTIONS = [
    ("Factual - fees", "What is the expense ratio of HDFC Flexi Cap Fund?"),
    ("Factual - minimums", "What is the minimum SIP for HDFC Small Cap Fund?"),
    ("Factual - charges", "What is the exit load of HDFC Large Cap Fund?"),
    ("Factual - tax", "What is the lock-in period for HDFC ELSS Tax Saver?"),
    ("Factual - people", "Who manages HDFC Balanced Advantage Fund?"),
    ("Factual - benchmark", "What benchmark does HDFC Flexi Cap Fund track?"),
    ("Procedural", "How do I download my capital-gains statement?"),
    ("Refusal - advice", "Should I invest in HDFC Small Cap Fund?"),
    ("Refusal - performance", "What is the 1 year return of HDFC Large Cap Fund?"),
    ("Refusal - out of scope", "What is the expense ratio of HDFC Mid Cap Fund?"),
    ("Refusal - attribute not indexed", "What is the ticker symbol of HDFC Large Cap Fund?"),
    ("Guard - PII", "my PAN is ABCDE1234F, what is the expense ratio?"),
    ("Guard - ambiguous", "HDFC fund"),
]

lines: list[str] = []
w = lines.append

w("# Sample Q&A - actual output")
w("")
w(f"Generated by `tests/gen_sample_qa.py` on {datetime.now():%d %B %Y} by calling")
w("the real pipeline (`src.query.answer.answer_question`) once per question.")
w(f"Provider at generation time: `{get_llm().name}`.")
w("")
w("Nothing in this file is written by hand. To regenerate it:")
w("")
w("```")
w("python tests/gen_sample_qa.py")
w("```")
w("")
w("Wording varies with the provider. The offline `StubLLM` quotes the source")
w("chunk almost literally; a hosted model paraphrases. The guardrails - one")
w("citation, the sentence cap, the refusal text, the footer - hold either way,")
w("because none of them is left to the model.")
w("")

for heading, q in QUESTIONS:
    out = answer_question(q)
    w(f"## {heading}")
    w("")
    w(f"**Q.** {q}")
    w("")
    if out.blocked:
        w(f"_Blocked by the `{out.guard_kind}` guard, before retrieval._")
    else:
        w(f"_Top-1 distance {out.top_distance:.3f} "
          f"(threshold {config.DISTANCE_THRESHOLD}), {out.latency_ms:.0f} ms._")
    w("")
    w("**A.**")
    w("")
    for ln in out.text.strip().splitlines():
        w(f"> {ln}" if ln.strip() else ">")
    w("")

w("## What these demonstrate")
w("")
w("- Every answered reply carries exactly one `Source:` line and the")
w("  `Last updated from sources:` footer. The model is asked only for a chunk")
w("  id; the link is re-derived from our own metadata, so a fabricated")
w("  citation cannot become a real one.")
w("- Refusals are authored copy rather than model output, so they are")
w("  byte-identical on every run and contain no percentages (FR-6).")
w("- The PII reply has no `Source:` line - there is nothing to cite - and none")
w("  of the message is echoed back, logged or stored.")
w("- `ticker symbol` is refused even though the scheme name appears in the")
w("  query and retrieval does return a nearby chunk. The attribute is simply")
w("  not in the corpus, and no distance threshold can catch that, so it is")
w("  handled as a guard rather than as a similarity cutoff.")
w("")

out_path = ROOT / "sample_qa.md"
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out_path} ({len(QUESTIONS)} questions, provider={get_llm().name})")
